xcopy /D  /Y d:\vybory\templ/*.*  /public_html/wp-content/themes/twentyfourteen/
xcopy /D  /Y d:/vybory/templ/js/*.*  /public_html/wp-content/themes/twentyfourteen/js/
xcopy /D  /Y d:/vybory/stylesheets/*.*  /public_html/wp-content/themes/twentyfourteen/css/
xcopy /D  /Y d:/vybory/templ/js/glavn.js /public_html/wp-content/plugins/vybory/js/
xcopy /D  /Y d:/vybory/vybory.php /public_html/wp-content/plugins/vybory/
xcopy /D  /Y d:/vybory/diln.csv /public_html/wp-content/plugins/vybory/
xcopy /D  /Y d:/vybory/login/*.* /public_html/wp-content/plugins/vybory/login/
xcopy /D  /Y d:/vybory/test.php /public_html/
xcopy /D  /Y d:/vybory/diln.csv /public_html/
xcopy /D  /Y d:/vybory/*.php /public_html/wp-content/plugins/vybory/
