xcopy /D  /Y d:\vybory\templ\*.*  d:\usr\www\s1.localhost\wp-content\themes\twentyfourteen\
xcopy /D  /Y d:\vybory\templ\js\*.*  d:\usr\www\s1.localhost\wp-content\themes\twentyfourteen\js\
xcopy /D  /Y d:\vybory\stylesheets\*.*  d:\usr\www\s1.localhost\wp-content\themes\twentyfourteen\css\
xcopy /D  /Y d:\vybory\templ\js\glavn.js d:\usr\www\s1.localhost\wp-content\plugins\vybory\js\
xcopy /D  /Y d:\vybory\vybory.php d:\usr\www\s1.localhost\wp-content\plugins\vybory\
xcopy /D  /Y d:\vybory\diln.csv d:\usr\www\s1.localhost\wp-content\plugins\vybory\
xcopy /D  /Y d:\vybory\login\*.* d:\usr\www\s1.localhost\wp-content\plugins\vybory\login\
xcopy /D  /Y d:\vybory\test.php d:\usr\www\s1.localhost\
xcopy /D  /Y d:\vybory\diln.csv d:\usr\www\s1.localhost\
xcopy /D  /Y d:\vybory\*.php d:\usr\www\s1.localhost\wp-content\plugins\vybory\
